### ISSUE TITLE
A paper information has been updated.

### ISSUE THREAD

**Issue by YichaoCai1** [jingyi0000/VLM_survey#10]
Hi, thank you for organizing this code repository! 

I would like to inform you that the information for an article titled "_CLAP: Contrastive Learning with Augmented Prompts for Robustness on Pretrained Vision-Language Models_" (categorized in "Transfer with Text Prompt Tuning" ) has been updated to "_CLAP: Isolating Content from Style through Contrastive Learning with Augmented Prompts_". 

Recently, this work was accepted by ECCV 2024, and we have provided the code (https://github.com/YichaoCai1/CLAP).

Could you please kindly update this information? Thanks again!

**Comment by jingyi0000** [comment]
Hi, thanks for letting me know. I have updated the information of this paper.
