### ISSUE TITLE
Add CVPR 2023 highlight paper

### ISSUE THREAD

**Issue by hellomuffin** [jingyi0000/VLM_survey#16]
Thank you for the great repo! Could you add our CVPR 2023 highlight paper,  that treats EXIF metadata as text, and pretrains an image-metadata CLIP encoder to support multiple low-level imaging downstream tasks?

Paper name: EXIF as Language: Learning Cross-Modal Associations Between Images and Camera Metadata
Paper link: https://arxiv.org/abs/2301.04647
github: https://github.com/hellomuffin/exif-as-language

**Comment by jingyi0000** [comment]
Hi, thanks for sharing! Have added it into our repo.
