### ISSUE TITLE
Can you Add LRV-Instruction to your Repo or Arxiv

### ISSUE THREAD

**Issue by FuxiaoLiu** [jingyi0000/VLM_survey#5]
Paper: Mitigating Hallucination in Large Multi-Modal Models via Robust Instruction Tuning
link: https://arxiv.org/pdf/2306.14565.pdf
Name: LRV-Instruction
Focus: Multimodal
Notes: Our paper (published in June) introduced GAVIE to evaluate hallucination of Large Vision and Language Model.. We are also the first to mitigate the hallucination of LVLMs by introducing LRV-Instruction.

bib:
[https://github.com/Article{liu2023aligning](https://github.com/Article%7Bliu2023aligning),
title={Aligning Large Multi-Modal Model with Robust Instruction Tuning},
author={Liu, Fuxiao and Lin, Kevin and Li, Linjie and Wang, Jianfeng and Yacoob, Yaser and Wang, Lijuan},
journal={arXiv preprint arXiv:2306.14565},
year={2023}
}

**Comment by jingyi0000** [comment]
Hi, thanks for sharing this paper. We have added it into the Repo.
