### ISSUE TITLE
Could you add a paper about applying VLMs for image restoration

### ISSUE THREAD

**Issue by Algolzw** [jingyi0000/VLM_survey#6]
It's (might be) the first paper using VLMs to improve image restoration performance.

Paper: Controlling Vision-Language Models for Universal Image Restoration
arXiv: https://arxiv.org/abs/2310.01018
Code: https://github.com/Algolzw/daclip-uir
Website: https://algolzw.github.io/daclip-uir

Thanks!

**Comment by jingyi0000** [comment]
Hi, thanks for sharing. We have added this paper into the Repo.
