### ISSUE TITLE
A Missing ICLR 2023 Paper (Maybe)

### ISSUE THREAD

**Issue by penghui-yang** [jingyi0000/VLM_survey#7]
Hi, thanks for this perfect repo!

If I did not miss anything important, I found a paper about prompt tuning which is not included in the repo. Its title is "LPT: Long-tailed Prompt Tuning for Image Classification" and it is published in ICLR 2023. If suitable, you may consider adding it to the repo.

Looking forward to receiving your reply.

**Comment by jingyi0000** [comment]
Hi, thanks for sharing. We have added this paper to the Repo.
