### ISSUE TITLE
Is VL-PET suitable for the Transfer Learning section?

### ISSUE THREAD

**Issue by HenryHZY** [jingyi0000/VLM_survey#9]
Hi @jingyi0000 , thanks for your great project.

I kindly request if you can add the ICCV23 paper "VL-PET: Vision-and-Language Parameter-Efficient Tuning via Granularity Control" to the Transfer Learning section". For you quick reference, VL-PET is an Adapter-like module designed for VL tasks.

Github: https://github.com/HenryHZY/VL-PET

**Comment by jingyi0000** [comment]
Hi @HenryHZY, thank you for sharing. We've added this paper to the repository.

**Comment by HenryHZY** [comment]
Thank you for your quick reply!
